// Generated by CoffeeScript 1.7.1
(function() {
  var Person, Woman, woman;

  if (typeof process !== "undefined") {
    Person = require("./Person.js").Person;
    Woman = require("./Woman.js").Woman;
  } else {
    Woman = window.Woman;
    Person = window.Person;
  }

  woman = new Woman("michelle");

  if (woman instanceof Person) {
    console.log(woman.walk());
  }

}).call(this);
