// Generated by CoffeeScript 1.7.1
(function() {
  var Person, Woman,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof process !== "undefined") {
    Person = require("./Person.js").Person;
  } else {
    Person = window.Person;
  }

  Woman = (function(_super) {
    __extends(Woman, _super);

    function Woman(name) {
      Woman.__super__.constructor.call(this, name);
    }

    Woman.prototype.walk = function() {
      return "" + this.name + " is walking like a runway model";
    };

    return Woman;

  })(Person);

  if (typeof process !== "undefined") {
    exports.Woman = Woman;
  } else {
    window.Woman = Woman;
  }

}).call(this);
